### PR TITLE
Fix issue of invalid w3c standard generated IDs.

### PR DESCRIPTION
**Pull request by arnab003**
- IDs now starts with 'fc'
- Modifies jasmine test case to incorporate change in generated ID.

### CODE REVIEW

**Comment by shamasis** [comment]
What? Did you realise that you are generating invalid UUID by modifying the generated UUID function? This is like changing the whole meaning of the function.

Why is this being done. UUID function does not conflict with anything. If this is to identify elements during tests, there are better method than adding this debt. 

Also, why "fc_"? This is a generic module called RedRaphael and we should try avoid introducing FusionCharts specific things here.

**Comment by shamasis** [comment]
In case you want to make the IDs w3c specific, kindly resend the PR by locating all the places where ID is being set in places and prefix `rr-` in hose places. As a shortcut, you might create a new function called `elementId‘ and that can do the prefixing as such replacing direct calls to UUID function using this new function. 

Cheers! Hope it helps.

**Comment by shamasis** [comment]
Your code will look sexier as you'll replace calls to createUUID by doing

`el.setAttribute('id', elementId(createUUID))`
and `return elementId('90- …')`

**Comment by arnab003** [comment]
@shamasis Thank you for your suggestion. I will do the appropriate change.

**Pull request closed without merging**
