### PR TITLE
Changed the default 0.01 pixel value to 0.5.

### PR DESCRIPTION
**Pull request by arnab003**

### CODE REVIEW

**Comment by shamasis** [comment]
@arnab003 would appreciate if you could cite and elaborate the reason for the same on PR description. Also, increasing to 0.5 has calculation side-effects. Hope you've accounted for the same.

**Comment by arnab003** [comment]
@shamasis Actually in my previous commit, which is already merged, I have made few changes.
The reason behind the changes is -
Since, stroke-linecap="round" is used, "lineDashLen" cannot be <= "lineThickness" as linecap depends on "lineThickness".
If condition arises when "lineDashLen" <= "lineThickness", the "lineDashLen" will be always equals to "lineThickness".

Now, when "lineDashLen" and "lineThickness", both are provided with value "1", the dashed line is merely visible or invisible for monitor of resolution 1360x768 but it is properly visible in higher resolution monitors and when the browser page is zoomed, the dashed line becomes visible again in 1360x768 resolution monitor. Thus, to overcome this problem of invisibility of dashed line, the minimum length of dashed line excluding line-cap is set to 0.5.

**Comment by shamasis** [comment]
A check could be met that if line thickness is less than 0.5 then line cap should go as low as the line thickness. Will possibly avoid unwanted side effects.

**Comment by arnab003** [comment]
Closing this pull request as this commit renders a dashed line with dash length 1.5 for attribute value 1 of "lineDashLen" to make it visible for low resolution monitor. So, to avoid resolution specific rendering of dash line, it is closed.

**Pull request closed without merging**
