### PR TITLE
Fix flow of multiline text including RTL characters. Currently fixed for...

### PR DESCRIPTION
**Pull request by nilanjanfc**
... Webkit based browsers.

Tested primarily on current versions of Chrome, Safari, Opera and Firefox (no issue). The issue in IE is yet to be resolved. The fix doesn't require dir="rtl" to be set on container or use of <bdo> to enable proper flow of the text with RTL characters. The unicode-bidi algorithm of the browsers handle them as required. The fix here breaks the continuity of successive <tspan> elements for text with RTL characters to be displayed in multiline, as required by the unicode-bidi algorithm of the browsers. This is done by injecting dummy <tspan> element with LTR character, in between two consecutive <tspan>  s with RTL text (or part of text containing RTL characters).

### CODE REVIEW

**Comment by shamasis** [comment]
@nilanjanfc - how about checking `getComputedStyle` for `text-direction` attribute to sense text direction when not sent via attrs?

**Comment by nilanjanfc** [comment]
@shamasis - I shall see to it in detail as soon as I return from vacation and do the needful.

**Comment by nilanjanfc** [comment]
@shamasis - I am a bit unsure of if we can check `text-direction` (not being a CSS property) from the CSSStyleDeclaration object returned by `getComputedStyle()`! However, I feel like checking `text-direction` instead of `direction`, on `params`, to align with the property naming convention in Raphael and be specific on the purpose of the attribute.

**Comment by shamasis** [comment]
@nilanjanfc - I see that `getComputedStyle` works just fine to detect `text-direction` or non-css `direction` property - http://jsfiddle.net/m8Zwk/

Also, I agree with the renaming of attribute.

**Comment by nilanjanfc** [comment]
@shamasis - I am a bit confused. Please check the fiddle link, seems like not the right version. I don't see the non-css property `text-direction` working (/ implemented) in the fiddle. It's coded for the css property `direction`. Or am I missing the point?

**Pull request merged**
