### PR TITLE
Fix paper animation in VML.

### PR DESCRIPTION
**Pull request by arnab003**
- Change attr fn name to setDimension.
- Check for valid width, height during setting of container style in VML.

### CODE REVIEW

**Comment by shamasis** [comment]
Hey. Can you explain what issue caused this change?

**Comment by arnab003** [comment]
@shamasis Actually in 'R._engine.setSize' method if any of the arguments is found 'undefined' (width, height), it cannot set respective style to canvas for value 'undefined'. Throws error in IE - 'Invalid argument'.

**Comment by shamasis** [comment]
Ah. Have you tested what causes the undefined to be sent? You should fix that at source as well.

One more thing - IE throws error when setting styles on elements having inherited display none. I'm having a hunch that it MAY be affected with this change. Just test once.

**Comment by arnab003** [comment]
Actually, to make it more flexible, paper dimension can be changed by either by providing the required width/height or both. Thus when one parameter is set, other is 'undefined'. If it is ok, can you please merge the PR as further development is dependent on this fix? Thank you.

**Comment by shamasis** [comment]
Seems fair. I'm merging this. When you've got time, try adding unit tests for dimensions. They're missing currently.

**Comment by arnab003** [comment]
@shamasis Thank you! Ok, I will.

**Pull request merged**
